apiVersion: v1
kind: Service
metadata:
  name: samplenodejsapp
  namespace: namespace-workflow-1728767098045
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: samplenodejsapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000